# cat .github/workflows/main.yml | yq -I4 e '.' -

name: main
on: push

jobs:
  build:
    name: Build and test for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.x', 'pypy-2.7' ]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Run tests
        run: |
          python ./lobtests.py
